name: Docker

on:
  workflow_dispatch: {}
  push:
    tags: [ '*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ANDROID_MANIFEST_BRANCH: android-11.0.0_r48
  LOCAL_MANIFEST_BRANCH: 11.0.0

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 项目目录
        run: |
          mkdir ~/redroid && cd ~/redroid

      - name: 检查依赖
        run: |
          sudo apt-get install repo
          repo --version
          git-lfs -v

      - name: 初始化 Android 项目 # check supported branch in https://github.com/remote-android/redroid-patches.git
        run: |
          repo init -u https://android.googlesource.com/platform/manifest --depth=1 -b ${{ env.ANDROID_MANIFEST_BRANCH }}

      - name: 添加本地清单
        run: |
          git clone https://github.com/remote-android/local_manifests.git ~/redroid/.repo/local_manifests -b ${{ env.LOCAL_MANIFEST_BRANCH }}

      - name: 同步代码
        run: |
          repo sync -c

      - name: 应用补丁
        run: |
          git clone https://github.com/remote-android/redroid-patches.git ~/redroid-patches
          ~/redroid-patches/apply-patch.sh ~/redroid
