name: Docker

on:
  workflow_dispatch: {}
  push:
    tags: [ '*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ANDROID_BRANCH: android-11.0.0_r48

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 检查依赖
        run: |
          sudo apt-get update
          sudo apt-get install repo
          repo --version
          git-lfs -v

      - name: 初始化 Android 项目
        run: |
          repo init -u https://android.googlesource.com/platform/manifest --git-lfs --depth=1 -b ${{ android-11.0.0_r48 }}
